# Generated by Django 4.1 on 2022-11-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_actors', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='voice_actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voice_actors.voiceactor'),
            preserve_default=False,
        ),
    ]
