# Generated by Django 4.1 on 2022-11-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_voiceactor_show_character_voiced_by'),
        ('characters', '0004_voiceactor_character_voice_actor'),
    ]

    operations = [
    ]
