# Generated by Django 4.1 on 2022-11-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_merge_20221120_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='voice_actor',
        ),
        migrations.RemoveField(
            model_name='show',
            name='character',
        ),
    ]
