# Generated by Django 4.1 on 2022-11-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_character_voice_actor_remove_show_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='voiced_by',
        ),
    ]
