# Generated by Django 4.1 on 2022-11-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_character_voiced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='voiced_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_played', to='characters.voiceactor'),
            preserve_default=False,
        ),
    ]
