# Generated by Django 4.1 on 2022-11-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_actors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceActor',
        ),
    ]
